### ISSUE TITLE
family check too?

### ISSUE THREAD

**Issue by melina-leite** [speckerf/treemendous#28]
Dear treemendous team,

first, thanks for creating such a great tool! Easy to use and fast!
I'm new in this species harmonization world and I'm using it to homogenize species names of trees from different forest plots, and I was wondering if it would be possible to check family names with the backbones. Some plots I have, have the same species but they differ in family names and it would be nice to have it harmonized too for further analysis (like creating a phylogenetic tree with `V.PhyloMaker2`which requests correct family names). 
Do you think it could be implemented in future versions of the package? 

Best wishes,
Melina

**Comment by speckerf** [comment]
Dear Melina

Thanks a lot for reaching out, it's great to hear you are using the tool. 

Although there is no direct functionality to match family names in the current version of the package, the package could still help you in this case. The database `Treemendous.Trees` (which is loaded with the package) contains the columns `WFO_Family`, `WCVP_Family` and `GBIF_Family` and you can use these columns to add the family names to the matched output species list.

V.PhyloMaker2 can create trees for three different nomenclature systems, one of which is The Plant List (which was [replaced](https://wfoplantlist.org/plant-list/background) by WorldFloraOnline (WFO)). So you could standardize according to `WFO` and then add the corresponding family names from the column `WFO_Family`. I have attached a script on how to do it (as a .txt file because github doesn't allow me to upload .R files here
[family_phylo.txt](https://github.com/speckerf/treemendous/files/13250281/family_phylo.txt)
).  Please let me know what you think about this workaround.

Best, Felix

**Comment by melina-leite** [comment]
Thanks a lot, Felix!
I'll have a better look at the script (next week), but it seems it is exactly what I need!!
:)

**Comment by melina-leite** [comment]
Hi Felix, 
I'm back to thank you again and to say that everything worked very well using the script example you sent! 
Just to add one note: the authors of V.PhyloMaker2 created a repo with more megatrees, including the plants megatree using the WCVP backbone: https://github.com/megatrees/plant_20221214. They mention that in their most recent publication ([Jin & Qian 2023](https://www.sciencedirect.com/science/article/pii/S2468265922001329?via%3Dihub)).
Best,
Melina
